openapi: 3.0.0
info:
  description: API for Monkey Exchange
  version: v1-oas3
  title: Monkey Exchange - Authentication
tags:
  - name: Token and Refresh Token
    description: Token and Refresh Token
paths:
  /oauth/token:
    post:
      tags:
        - Token
      summary: Token and Refresh Token
      requestBody:
        description: Retrieve token body
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
                - type: object
                  description: Body for token generation
                  required:
                    - client_id
                    - client_secret
                    - username
                    - password
                    - grant_type
                    - scope
                  properties:
                    client_id:
                      type: string
                      description: Provided by Monkey.
                    client_secret:
                      type: string
                      description: Provided by Monkey.
                    username:
                      type: string
                      description: User's email to be used.
                    password:
                      type: string
                      description: User's password to be used.
                    grant_type:
                      type: string
                      description: Default value "password".
                    scope:
                      type: string
                      description: Default value "server".
                - type: object
                  description: Body for token generation using the refresh token
                  required:
                    - client_id
                    - client_secret
                    - grant_type
                    - refresh_token
                  properties:
                    client_id:
                      type: string
                      description: Provided by Monkey.
                    client_secret:
                      type: string
                      description: Provided by Monkey.
                    grant_type:
                      type: string
                      description: Default value "refresh_token"
                    refresh_token:
                      type: string
                      description: Refresh token returned in the token call.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token to be used in all requests.
                  token_type:
                    type: string
                    description: Token type.
                    default: bearer
                  refresh_token:
                    type: string
                    description: Token used for revalidation.
                  expires_in:
                    type: integer
                    format: int64
                    description: Token validity time in seconds.
                  scope:
                    type: string
                    description: Token usage scope.
                    default: server
        '400':
          description: Request invalid or malformed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error type.
                  error_description:
                    type: string
                    description: Error description.
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: integer
                    format: int64
                    description: Time when the error occurred.
                  status:
                    type: integer
                    description: Error status code.
                  error:
                    type: string
                    description: Error type.
                  message:
                    type: string
                    description: Error description.
                  path:
                    type: string
                    description: URL path.
  /profiles:
    get:
      tags:
        - Profile Listing
      summary: List user profiles
      description: This item exemplifies the endpoint that allows querying all companies of a user.
      parameters:
        - name: program
          in: header
          description: Identifier of the program to be accessed. See <a href='/authentication#program' target='_blank'>here</a> for how programs work.
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: Your access token. See <a href='/authentication#token' target='_blank'>here</a> for how to use the access token.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200 - OK: The call was successful.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  companies:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Company identifier.
                        userId:
                          type: integer
                          description: User identifier.
                        status:
                          type: string
                          description: Company status. Possible values are `ACTIVE` - Active company or `INACTIVE` - Inactive company.
                        type:
                          type: string
                          description: Company profile type. Possible values are `SPONSOR` - Payer or `SELLER` - Assignor or `BUYER` - Investor.
                        name:
                          type: string
                          description: Company trade name.
                        companyName:
                          type: string
                          description: Company trade name.
                        governmentId:
                          type: string
                          description: Company CNPJ or CPF.
                        role:
                          type: string
                          description: Permission level.</br>`ADMIN` - Administrator</br>`EXECUTE` - Execution</br>`SELECTOR` - Selector</br>`VIEW` - Viewer</br>`BACK_OFFICE` - Backoffice.
                        adhesionTerm:
                          type: boolean
                          description: Company requires adhesion term.
                        programAdmin:
                          type: boolean
                          description: User is an administrator in this company.
                        createdAt:
                          description: Resource creation date.
                          type: string
                          format: date-time
                          readOnly: true
                        _links:
                          type: array
                          description: Resources available through HATEOAS.<br>To learn more click <a href='/api#hypermedia-hateoas' target='_blank'>here</a>.
                          items:
                            type: object
                            properties:
                              href:
                                type: string
                              rel:
                                type: string
                              templated:
                                type: boolean
        '401':
          description: '401 - Unauthorized: The user and password or access token are invalid. See <a href=''/authentication#token'' target=''_blank''>here</a> for how to use the access token.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error type.
                  error_description:
                    type: string
                    description: Error description.
        '403':
          description: '403 - Forbidden: API access is not allowed or user is blocked.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    description: Error type.
                  description:
                    type: string
                    description: Error description.
                  notifications:
                    type: array
                    items:
                      type: string
                      description: Error details.
        '500':
          description: '500 - Internal Server Error: There was an internal server error processing the request. <a href=''https://monkeyexchange.statuspage.io/'' target=''_blank''>Check server status</a>.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    description: Error type.
                  description:
                    type: string
                    description: Error description.
                  notifications:
                    type: array
                    items:
                      type: string
                      description: Error details.
servers:
  - url: https://hmg-zuul.monkeyecx.com/uaa
    description: Staging Server
  - url: https://zuul.monkey.exchange/uaa
    description: Production Server
